import type { Metadata } from "next";
import { Roboto, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation";
import Footer from "../components/Footer";
import Providers from "../components/Providers";
import { notFound } from "next/navigation";
import { locales } from "@/i18n";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: { url: "/favicon.svg", type: "image/svg+xml" },
  },
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!locales.includes(locale)) notFound();

  // This tells next-intl to use the URL param instead of headers()
  setRequestLocale(locale);
  const messages = await getMessages({ locale });

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <html lang={locale} className="bg-neutral-50 dark:bg-neutral-900">
        <body
          className={`${roboto.variable} ${playfair.variable} antialiased flex flex-col min-h-dvh`}
        >
          <Providers>
            <Navigation />
            <main className="flex-1">{children}</main>
            <Footer />
          </Providers>
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
